### ISSUE TITLE
Workflow not changing "Assigned to User"

### ISSUE THREAD

**Issue by gerhard84** [AdhocAdam/scsmoutofoffice#1]
When importing the sealed MPs, I can see the WF is running but it does not change the "Assigned to User". All the other steps have been completed as stated in the instructions.

I downloaded the unsealed MPs and found a possible issue.
Inside "AdhocAdam.WorkItemAssignmentPrevention.OOO.xml"  on line 108 and 114 there is a space between the variable and the array number:
    Remove-SCSMRelationshipObject -SMObject $assignedToUserRelationships [0]

I copied this script to ISE and when modifying the script it works:
    Remove-SCSMRelationshipObject -SMObject $assignedToUserRelationships[0]

The error I'm getting from ISE is as follow:
Remove-SCSMRelationshipObject : A positional parameter cannot be found that accepts argument '[0]'.

**Comment by AdhocAdam** [comment]
Thanks for your help @gerhard84 !
