### ISSUE TITLE
Wrong variable name in workflow

### ISSUE THREAD

**Issue by gerhard84** [AdhocAdam/scsmoutofoffice#2]
In the AdhocAdam.WorkItemAssignmentPrevention.OOO.xml under the ServiceRequestOOO Workflows, there is a wrong variable being called.

`import-module smlets
$srClass = Get-SCSMClass -name "System.WorkItem.ServiceRequest$"
$assignedToRelClass = Get-SCSMRelationshipClass "System.WorkItemAssignedToUser$"
$serviceRequest = Get-SCSMObject -class $irClass -filter "Name -eq '$Id'"`

On line 2 a variable $srClass is created but on line 4 a $irClass is being called, this creates an error, and the workflow does not complete.

**Comment by AdhocAdam** [comment]
Thanks for your help @gerhard84 !
